ryberg_path = "/data/users/kgruber/other-data"
results_path = "/data/users/kgruber/results"
data_path = "/data/users/kgruber/other-data"
era_path = "/data/users/kgruber/Data/era5"
mer_path = "/data/users/kgruber/Data/MERRA"